image: node

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  - npm run build
  - rm -rf public
  - cp build/index.html build/404.html
  - mv build public
  - npm install -g serve
  - serve -s public
  artifacts:
    paths:
    - public
