version: '3.3'

services:
  r-in-vr-react-xr:
    image: r-in-vr-react-xr
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - "3000:80"
    networks:
       - web
    labels: # for traefik, delete this if not needed
       - "traefik.enable=true" # Auto-search deactivated so we need to specify the service enable
       - "traefik.docker.network=web" # On the network web
       - "traefik.http.routers.vr2.rule=Host(`vr.achencraft.fr`) && Path(`/traefik`)"
       - "traefik.http.routers.vr2.tls=true" # Routeur https activé
       - "traefik.http.routers.vr2.tls.certresolver=default" # Cert resolver
       - "traefik.http.services.vr2.loadbalancer.server.port=3000"
networks:
    web:
      external:
        name: web
